# Generated by Django 5.1 on 2024-09-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('RF', 'refunded'), ('F', 'failed'), ('A', 'abandoned'), ('RV', 'revoked'), ('PA', 'preapproved'), ('OH', 'on_hold'), ('CA', 'canceled')], default='P', max_length=2)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
    ]
